//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaSistemi.KiralamaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kiralama", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Kiralama : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int kiralamaIdField;
        
        private int sirketIdField;
        
        private int musteriIdField;
        
        private int aracIdField;
        
        private System.DateTime verilisTarihiField;
        
        private System.Nullable<System.DateTime> geriAlisTarihiField;
        
        private int verilisKmField;
        
        private System.Nullable<int> sonKmField;
        
        private System.Nullable<int> ucretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AracKiralamaSistemi.KiralamaService.Sirket sirketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AracKiralamaSistemi.KiralamaService.Arac aracField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int kiralamaId {
            get {
                return this.kiralamaIdField;
            }
            set {
                if ((this.kiralamaIdField.Equals(value) != true)) {
                    this.kiralamaIdField = value;
                    this.RaisePropertyChanged("kiralamaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sirketId {
            get {
                return this.sirketIdField;
            }
            set {
                if ((this.sirketIdField.Equals(value) != true)) {
                    this.sirketIdField = value;
                    this.RaisePropertyChanged("sirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int musteriId {
            get {
                return this.musteriIdField;
            }
            set {
                if ((this.musteriIdField.Equals(value) != true)) {
                    this.musteriIdField = value;
                    this.RaisePropertyChanged("musteriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int aracId {
            get {
                return this.aracIdField;
            }
            set {
                if ((this.aracIdField.Equals(value) != true)) {
                    this.aracIdField = value;
                    this.RaisePropertyChanged("aracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime verilisTarihi {
            get {
                return this.verilisTarihiField;
            }
            set {
                if ((this.verilisTarihiField.Equals(value) != true)) {
                    this.verilisTarihiField = value;
                    this.RaisePropertyChanged("verilisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> geriAlisTarihi {
            get {
                return this.geriAlisTarihiField;
            }
            set {
                if ((this.geriAlisTarihiField.Equals(value) != true)) {
                    this.geriAlisTarihiField = value;
                    this.RaisePropertyChanged("geriAlisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int verilisKm {
            get {
                return this.verilisKmField;
            }
            set {
                if ((this.verilisKmField.Equals(value) != true)) {
                    this.verilisKmField = value;
                    this.RaisePropertyChanged("verilisKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> sonKm {
            get {
                return this.sonKmField;
            }
            set {
                if ((this.sonKmField.Equals(value) != true)) {
                    this.sonKmField = value;
                    this.RaisePropertyChanged("sonKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> ucret {
            get {
                return this.ucretField;
            }
            set {
                if ((this.ucretField.Equals(value) != true)) {
                    this.ucretField = value;
                    this.RaisePropertyChanged("ucret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public AracKiralamaSistemi.KiralamaService.Sirket sirket {
            get {
                return this.sirketField;
            }
            set {
                if ((object.ReferenceEquals(this.sirketField, value) != true)) {
                    this.sirketField = value;
                    this.RaisePropertyChanged("sirket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public AracKiralamaSistemi.KiralamaService.Arac arac {
            get {
                return this.aracField;
            }
            set {
                if ((object.ReferenceEquals(this.aracField, value) != true)) {
                    this.aracField = value;
                    this.RaisePropertyChanged("arac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sirket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sirket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int sirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sirketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresField;
        
        private ushort aracSayisiField;
        
        private System.Nullable<int> sirketPuaniField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sirketId {
            get {
                return this.sirketIdField;
            }
            set {
                if ((this.sirketIdField.Equals(value) != true)) {
                    this.sirketIdField = value;
                    this.RaisePropertyChanged("sirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sirketAdi {
            get {
                return this.sirketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.sirketAdiField, value) != true)) {
                    this.sirketAdiField = value;
                    this.RaisePropertyChanged("sirketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sehir {
            get {
                return this.sehirField;
            }
            set {
                if ((object.ReferenceEquals(this.sehirField, value) != true)) {
                    this.sehirField = value;
                    this.RaisePropertyChanged("sehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adres {
            get {
                return this.adresField;
            }
            set {
                if ((object.ReferenceEquals(this.adresField, value) != true)) {
                    this.adresField = value;
                    this.RaisePropertyChanged("adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public ushort aracSayisi {
            get {
                return this.aracSayisiField;
            }
            set {
                if ((this.aracSayisiField.Equals(value) != true)) {
                    this.aracSayisiField = value;
                    this.RaisePropertyChanged("aracSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> sirketPuani {
            get {
                return this.sirketPuaniField;
            }
            set {
                if ((this.sirketPuaniField.Equals(value) != true)) {
                    this.sirketPuaniField = value;
                    this.RaisePropertyChanged("sirketPuani");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Arac", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Arac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int aracIdField;
        
        private int sirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string markaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        private int minEhliyetYasiField;
        
        private short minYasSiniriField;
        
        private short gunlukMaxKmSiniriField;
        
        private int anlikKmField;
        
        private byte airbagSayisiField;
        
        private short bagajHacmiField;
        
        private byte koltukSayisiField;
        
        private int gunlukFiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AracKiralamaSistemi.KiralamaService.Sirket sirketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int aracId {
            get {
                return this.aracIdField;
            }
            set {
                if ((this.aracIdField.Equals(value) != true)) {
                    this.aracIdField = value;
                    this.RaisePropertyChanged("aracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sirketId {
            get {
                return this.sirketIdField;
            }
            set {
                if ((this.sirketIdField.Equals(value) != true)) {
                    this.sirketIdField = value;
                    this.RaisePropertyChanged("sirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string marka {
            get {
                return this.markaField;
            }
            set {
                if ((object.ReferenceEquals(this.markaField, value) != true)) {
                    this.markaField = value;
                    this.RaisePropertyChanged("marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int minEhliyetYasi {
            get {
                return this.minEhliyetYasiField;
            }
            set {
                if ((this.minEhliyetYasiField.Equals(value) != true)) {
                    this.minEhliyetYasiField = value;
                    this.RaisePropertyChanged("minEhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public short minYasSiniri {
            get {
                return this.minYasSiniriField;
            }
            set {
                if ((this.minYasSiniriField.Equals(value) != true)) {
                    this.minYasSiniriField = value;
                    this.RaisePropertyChanged("minYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public short gunlukMaxKmSiniri {
            get {
                return this.gunlukMaxKmSiniriField;
            }
            set {
                if ((this.gunlukMaxKmSiniriField.Equals(value) != true)) {
                    this.gunlukMaxKmSiniriField = value;
                    this.RaisePropertyChanged("gunlukMaxKmSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int anlikKm {
            get {
                return this.anlikKmField;
            }
            set {
                if ((this.anlikKmField.Equals(value) != true)) {
                    this.anlikKmField = value;
                    this.RaisePropertyChanged("anlikKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public byte airbagSayisi {
            get {
                return this.airbagSayisiField;
            }
            set {
                if ((this.airbagSayisiField.Equals(value) != true)) {
                    this.airbagSayisiField = value;
                    this.RaisePropertyChanged("airbagSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public short bagajHacmi {
            get {
                return this.bagajHacmiField;
            }
            set {
                if ((this.bagajHacmiField.Equals(value) != true)) {
                    this.bagajHacmiField = value;
                    this.RaisePropertyChanged("bagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public byte koltukSayisi {
            get {
                return this.koltukSayisiField;
            }
            set {
                if ((this.koltukSayisiField.Equals(value) != true)) {
                    this.koltukSayisiField = value;
                    this.RaisePropertyChanged("koltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int gunlukFiyat {
            get {
                return this.gunlukFiyatField;
            }
            set {
                if ((this.gunlukFiyatField.Equals(value) != true)) {
                    this.gunlukFiyatField = value;
                    this.RaisePropertyChanged("gunlukFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public AracKiralamaSistemi.KiralamaService.Sirket sirket {
            get {
                return this.sirketField;
            }
            set {
                if ((object.ReferenceEquals(this.sirketField, value) != true)) {
                    this.sirketField = value;
                    this.RaisePropertyChanged("sirket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KiralamaService.KiralamaWebServiceSoap")]
    public interface KiralamaWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertKiralama", ReplyAction="*")]
        AracKiralamaSistemi.KiralamaService.InsertKiralamaResponse InsertKiralama(AracKiralamaSistemi.KiralamaService.InsertKiralamaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertKiralama", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSistemi.KiralamaService.InsertKiralamaResponse> InsertKiralamaAsync(AracKiralamaSistemi.KiralamaService.InsertKiralamaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKiralama", ReplyAction="*")]
        bool DeleteKiralama(int kiralamaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKiralama", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteKiralamaAsync(int kiralamaId);
        
        // CODEGEN: Generating message contract since element name SelectAllKiralamasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllKiralamas", ReplyAction="*")]
        AracKiralamaSistemi.KiralamaService.SelectAllKiralamasResponse SelectAllKiralamas(AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllKiralamas", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSistemi.KiralamaService.SelectAllKiralamasResponse> SelectAllKiralamasAsync(AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequest request);
        
        // CODEGEN: Generating message contract since element name SelectKiralamaByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectKiralamaById", ReplyAction="*")]
        AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdResponse SelectKiralamaById(AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectKiralamaById", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdResponse> SelectKiralamaByIdAsync(AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKiralamaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKiralama", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.KiralamaService.InsertKiralamaRequestBody Body;
        
        public InsertKiralamaRequest() {
        }
        
        public InsertKiralamaRequest(AracKiralamaSistemi.KiralamaService.InsertKiralamaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKiralamaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSistemi.KiralamaService.Kiralama entity;
        
        public InsertKiralamaRequestBody() {
        }
        
        public InsertKiralamaRequestBody(AracKiralamaSistemi.KiralamaService.Kiralama entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKiralamaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKiralamaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.KiralamaService.InsertKiralamaResponseBody Body;
        
        public InsertKiralamaResponse() {
        }
        
        public InsertKiralamaResponse(AracKiralamaSistemi.KiralamaService.InsertKiralamaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKiralamaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertKiralamaResult;
        
        public InsertKiralamaResponseBody() {
        }
        
        public InsertKiralamaResponseBody(bool InsertKiralamaResult) {
            this.InsertKiralamaResult = InsertKiralamaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllKiralamasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllKiralamas", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequestBody Body;
        
        public SelectAllKiralamasRequest() {
        }
        
        public SelectAllKiralamasRequest(AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllKiralamasRequestBody {
        
        public SelectAllKiralamasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllKiralamasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllKiralamasResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.KiralamaService.SelectAllKiralamasResponseBody Body;
        
        public SelectAllKiralamasResponse() {
        }
        
        public SelectAllKiralamasResponse(AracKiralamaSistemi.KiralamaService.SelectAllKiralamasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllKiralamasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSistemi.KiralamaService.Kiralama[] SelectAllKiralamasResult;
        
        public SelectAllKiralamasResponseBody() {
        }
        
        public SelectAllKiralamasResponseBody(AracKiralamaSistemi.KiralamaService.Kiralama[] SelectAllKiralamasResult) {
            this.SelectAllKiralamasResult = SelectAllKiralamasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectKiralamaByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectKiralamaById", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequestBody Body;
        
        public SelectKiralamaByIdRequest() {
        }
        
        public SelectKiralamaByIdRequest(AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectKiralamaByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kiralamaId;
        
        public SelectKiralamaByIdRequestBody() {
        }
        
        public SelectKiralamaByIdRequestBody(int kiralamaId) {
            this.kiralamaId = kiralamaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectKiralamaByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectKiralamaByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdResponseBody Body;
        
        public SelectKiralamaByIdResponse() {
        }
        
        public SelectKiralamaByIdResponse(AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectKiralamaByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSistemi.KiralamaService.Kiralama SelectKiralamaByIdResult;
        
        public SelectKiralamaByIdResponseBody() {
        }
        
        public SelectKiralamaByIdResponseBody(AracKiralamaSistemi.KiralamaService.Kiralama SelectKiralamaByIdResult) {
            this.SelectKiralamaByIdResult = SelectKiralamaByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KiralamaWebServiceSoapChannel : AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KiralamaWebServiceSoapClient : System.ServiceModel.ClientBase<AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap>, AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap {
        
        public KiralamaWebServiceSoapClient() {
        }
        
        public KiralamaWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KiralamaWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KiralamaWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KiralamaWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSistemi.KiralamaService.InsertKiralamaResponse AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap.InsertKiralama(AracKiralamaSistemi.KiralamaService.InsertKiralamaRequest request) {
            return base.Channel.InsertKiralama(request);
        }
        
        public bool InsertKiralama(AracKiralamaSistemi.KiralamaService.Kiralama entity) {
            AracKiralamaSistemi.KiralamaService.InsertKiralamaRequest inValue = new AracKiralamaSistemi.KiralamaService.InsertKiralamaRequest();
            inValue.Body = new AracKiralamaSistemi.KiralamaService.InsertKiralamaRequestBody();
            inValue.Body.entity = entity;
            AracKiralamaSistemi.KiralamaService.InsertKiralamaResponse retVal = ((AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap)(this)).InsertKiralama(inValue);
            return retVal.Body.InsertKiralamaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSistemi.KiralamaService.InsertKiralamaResponse> AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap.InsertKiralamaAsync(AracKiralamaSistemi.KiralamaService.InsertKiralamaRequest request) {
            return base.Channel.InsertKiralamaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSistemi.KiralamaService.InsertKiralamaResponse> InsertKiralamaAsync(AracKiralamaSistemi.KiralamaService.Kiralama entity) {
            AracKiralamaSistemi.KiralamaService.InsertKiralamaRequest inValue = new AracKiralamaSistemi.KiralamaService.InsertKiralamaRequest();
            inValue.Body = new AracKiralamaSistemi.KiralamaService.InsertKiralamaRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap)(this)).InsertKiralamaAsync(inValue);
        }
        
        public bool DeleteKiralama(int kiralamaId) {
            return base.Channel.DeleteKiralama(kiralamaId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteKiralamaAsync(int kiralamaId) {
            return base.Channel.DeleteKiralamaAsync(kiralamaId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSistemi.KiralamaService.SelectAllKiralamasResponse AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap.SelectAllKiralamas(AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequest request) {
            return base.Channel.SelectAllKiralamas(request);
        }
        
        public AracKiralamaSistemi.KiralamaService.Kiralama[] SelectAllKiralamas() {
            AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequest inValue = new AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequest();
            inValue.Body = new AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequestBody();
            AracKiralamaSistemi.KiralamaService.SelectAllKiralamasResponse retVal = ((AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap)(this)).SelectAllKiralamas(inValue);
            return retVal.Body.SelectAllKiralamasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSistemi.KiralamaService.SelectAllKiralamasResponse> AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap.SelectAllKiralamasAsync(AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequest request) {
            return base.Channel.SelectAllKiralamasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSistemi.KiralamaService.SelectAllKiralamasResponse> SelectAllKiralamasAsync() {
            AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequest inValue = new AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequest();
            inValue.Body = new AracKiralamaSistemi.KiralamaService.SelectAllKiralamasRequestBody();
            return ((AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap)(this)).SelectAllKiralamasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdResponse AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap.SelectKiralamaById(AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequest request) {
            return base.Channel.SelectKiralamaById(request);
        }
        
        public AracKiralamaSistemi.KiralamaService.Kiralama SelectKiralamaById(int kiralamaId) {
            AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequest inValue = new AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequest();
            inValue.Body = new AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequestBody();
            inValue.Body.kiralamaId = kiralamaId;
            AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdResponse retVal = ((AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap)(this)).SelectKiralamaById(inValue);
            return retVal.Body.SelectKiralamaByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdResponse> AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap.SelectKiralamaByIdAsync(AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequest request) {
            return base.Channel.SelectKiralamaByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdResponse> SelectKiralamaByIdAsync(int kiralamaId) {
            AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequest inValue = new AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequest();
            inValue.Body = new AracKiralamaSistemi.KiralamaService.SelectKiralamaByIdRequestBody();
            inValue.Body.kiralamaId = kiralamaId;
            return ((AracKiralamaSistemi.KiralamaService.KiralamaWebServiceSoap)(this)).SelectKiralamaByIdAsync(inValue);
        }
    }
}
