//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaSistemi.AracService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Arac", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Arac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int aracIdField;
        
        private int sirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string markaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        private int minEhliyetYasiField;
        
        private short minYasSiniriField;
        
        private short gunlukMaxKmSiniriField;
        
        private int anlikKmField;
        
        private byte airbagSayisiField;
        
        private short bagajHacmiField;
        
        private byte koltukSayisiField;
        
        private int gunlukFiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AracKiralamaSistemi.AracService.Sirket sirketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int aracId {
            get {
                return this.aracIdField;
            }
            set {
                if ((this.aracIdField.Equals(value) != true)) {
                    this.aracIdField = value;
                    this.RaisePropertyChanged("aracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sirketId {
            get {
                return this.sirketIdField;
            }
            set {
                if ((this.sirketIdField.Equals(value) != true)) {
                    this.sirketIdField = value;
                    this.RaisePropertyChanged("sirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string marka {
            get {
                return this.markaField;
            }
            set {
                if ((object.ReferenceEquals(this.markaField, value) != true)) {
                    this.markaField = value;
                    this.RaisePropertyChanged("marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int minEhliyetYasi {
            get {
                return this.minEhliyetYasiField;
            }
            set {
                if ((this.minEhliyetYasiField.Equals(value) != true)) {
                    this.minEhliyetYasiField = value;
                    this.RaisePropertyChanged("minEhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public short minYasSiniri {
            get {
                return this.minYasSiniriField;
            }
            set {
                if ((this.minYasSiniriField.Equals(value) != true)) {
                    this.minYasSiniriField = value;
                    this.RaisePropertyChanged("minYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public short gunlukMaxKmSiniri {
            get {
                return this.gunlukMaxKmSiniriField;
            }
            set {
                if ((this.gunlukMaxKmSiniriField.Equals(value) != true)) {
                    this.gunlukMaxKmSiniriField = value;
                    this.RaisePropertyChanged("gunlukMaxKmSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int anlikKm {
            get {
                return this.anlikKmField;
            }
            set {
                if ((this.anlikKmField.Equals(value) != true)) {
                    this.anlikKmField = value;
                    this.RaisePropertyChanged("anlikKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public byte airbagSayisi {
            get {
                return this.airbagSayisiField;
            }
            set {
                if ((this.airbagSayisiField.Equals(value) != true)) {
                    this.airbagSayisiField = value;
                    this.RaisePropertyChanged("airbagSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public short bagajHacmi {
            get {
                return this.bagajHacmiField;
            }
            set {
                if ((this.bagajHacmiField.Equals(value) != true)) {
                    this.bagajHacmiField = value;
                    this.RaisePropertyChanged("bagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public byte koltukSayisi {
            get {
                return this.koltukSayisiField;
            }
            set {
                if ((this.koltukSayisiField.Equals(value) != true)) {
                    this.koltukSayisiField = value;
                    this.RaisePropertyChanged("koltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int gunlukFiyat {
            get {
                return this.gunlukFiyatField;
            }
            set {
                if ((this.gunlukFiyatField.Equals(value) != true)) {
                    this.gunlukFiyatField = value;
                    this.RaisePropertyChanged("gunlukFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public AracKiralamaSistemi.AracService.Sirket sirket {
            get {
                return this.sirketField;
            }
            set {
                if ((object.ReferenceEquals(this.sirketField, value) != true)) {
                    this.sirketField = value;
                    this.RaisePropertyChanged("sirket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sirket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sirket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int sirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sirketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresField;
        
        private ushort aracSayisiField;
        
        private System.Nullable<int> sirketPuaniField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sirketId {
            get {
                return this.sirketIdField;
            }
            set {
                if ((this.sirketIdField.Equals(value) != true)) {
                    this.sirketIdField = value;
                    this.RaisePropertyChanged("sirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sirketAdi {
            get {
                return this.sirketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.sirketAdiField, value) != true)) {
                    this.sirketAdiField = value;
                    this.RaisePropertyChanged("sirketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sehir {
            get {
                return this.sehirField;
            }
            set {
                if ((object.ReferenceEquals(this.sehirField, value) != true)) {
                    this.sehirField = value;
                    this.RaisePropertyChanged("sehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adres {
            get {
                return this.adresField;
            }
            set {
                if ((object.ReferenceEquals(this.adresField, value) != true)) {
                    this.adresField = value;
                    this.RaisePropertyChanged("adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public ushort aracSayisi {
            get {
                return this.aracSayisiField;
            }
            set {
                if ((this.aracSayisiField.Equals(value) != true)) {
                    this.aracSayisiField = value;
                    this.RaisePropertyChanged("aracSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> sirketPuani {
            get {
                return this.sirketPuaniField;
            }
            set {
                if ((this.sirketPuaniField.Equals(value) != true)) {
                    this.sirketPuaniField = value;
                    this.RaisePropertyChanged("sirketPuani");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AracService.AracWebServiceSoap")]
    public interface AracWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertArac", ReplyAction="*")]
        AracKiralamaSistemi.AracService.InsertAracResponse InsertArac(AracKiralamaSistemi.AracService.InsertAracRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertArac", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSistemi.AracService.InsertAracResponse> InsertAracAsync(AracKiralamaSistemi.AracService.InsertAracRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteArac", ReplyAction="*")]
        bool DeleteArac(int aracId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteArac", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAracAsync(int aracId);
        
        // CODEGEN: Generating message contract since element name SelectAllAracsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllAracs", ReplyAction="*")]
        AracKiralamaSistemi.AracService.SelectAllAracsResponse SelectAllAracs(AracKiralamaSistemi.AracService.SelectAllAracsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllAracs", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSistemi.AracService.SelectAllAracsResponse> SelectAllAracsAsync(AracKiralamaSistemi.AracService.SelectAllAracsRequest request);
        
        // CODEGEN: Generating message contract since element name SelectAracByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAracById", ReplyAction="*")]
        AracKiralamaSistemi.AracService.SelectAracByIdResponse SelectAracById(AracKiralamaSistemi.AracService.SelectAracByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAracById", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSistemi.AracService.SelectAracByIdResponse> SelectAracByIdAsync(AracKiralamaSistemi.AracService.SelectAracByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAracRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertArac", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.AracService.InsertAracRequestBody Body;
        
        public InsertAracRequest() {
        }
        
        public InsertAracRequest(AracKiralamaSistemi.AracService.InsertAracRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAracRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSistemi.AracService.Arac entity;
        
        public InsertAracRequestBody() {
        }
        
        public InsertAracRequestBody(AracKiralamaSistemi.AracService.Arac entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAracResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAracResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.AracService.InsertAracResponseBody Body;
        
        public InsertAracResponse() {
        }
        
        public InsertAracResponse(AracKiralamaSistemi.AracService.InsertAracResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAracResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertAracResult;
        
        public InsertAracResponseBody() {
        }
        
        public InsertAracResponseBody(bool InsertAracResult) {
            this.InsertAracResult = InsertAracResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllAracsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllAracs", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.AracService.SelectAllAracsRequestBody Body;
        
        public SelectAllAracsRequest() {
        }
        
        public SelectAllAracsRequest(AracKiralamaSistemi.AracService.SelectAllAracsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllAracsRequestBody {
        
        public SelectAllAracsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllAracsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllAracsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.AracService.SelectAllAracsResponseBody Body;
        
        public SelectAllAracsResponse() {
        }
        
        public SelectAllAracsResponse(AracKiralamaSistemi.AracService.SelectAllAracsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllAracsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSistemi.AracService.Arac[] SelectAllAracsResult;
        
        public SelectAllAracsResponseBody() {
        }
        
        public SelectAllAracsResponseBody(AracKiralamaSistemi.AracService.Arac[] SelectAllAracsResult) {
            this.SelectAllAracsResult = SelectAllAracsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAracByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAracById", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.AracService.SelectAracByIdRequestBody Body;
        
        public SelectAracByIdRequest() {
        }
        
        public SelectAracByIdRequest(AracKiralamaSistemi.AracService.SelectAracByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAracByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int aracId;
        
        public SelectAracByIdRequestBody() {
        }
        
        public SelectAracByIdRequestBody(int aracId) {
            this.aracId = aracId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAracByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAracByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.AracService.SelectAracByIdResponseBody Body;
        
        public SelectAracByIdResponse() {
        }
        
        public SelectAracByIdResponse(AracKiralamaSistemi.AracService.SelectAracByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAracByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSistemi.AracService.Arac SelectAracByIdResult;
        
        public SelectAracByIdResponseBody() {
        }
        
        public SelectAracByIdResponseBody(AracKiralamaSistemi.AracService.Arac SelectAracByIdResult) {
            this.SelectAracByIdResult = SelectAracByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AracWebServiceSoapChannel : AracKiralamaSistemi.AracService.AracWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AracWebServiceSoapClient : System.ServiceModel.ClientBase<AracKiralamaSistemi.AracService.AracWebServiceSoap>, AracKiralamaSistemi.AracService.AracWebServiceSoap {
        
        public AracWebServiceSoapClient() {
        }
        
        public AracWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AracWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSistemi.AracService.InsertAracResponse AracKiralamaSistemi.AracService.AracWebServiceSoap.InsertArac(AracKiralamaSistemi.AracService.InsertAracRequest request) {
            return base.Channel.InsertArac(request);
        }
        
        public bool InsertArac(AracKiralamaSistemi.AracService.Arac entity) {
            AracKiralamaSistemi.AracService.InsertAracRequest inValue = new AracKiralamaSistemi.AracService.InsertAracRequest();
            inValue.Body = new AracKiralamaSistemi.AracService.InsertAracRequestBody();
            inValue.Body.entity = entity;
            AracKiralamaSistemi.AracService.InsertAracResponse retVal = ((AracKiralamaSistemi.AracService.AracWebServiceSoap)(this)).InsertArac(inValue);
            return retVal.Body.InsertAracResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSistemi.AracService.InsertAracResponse> AracKiralamaSistemi.AracService.AracWebServiceSoap.InsertAracAsync(AracKiralamaSistemi.AracService.InsertAracRequest request) {
            return base.Channel.InsertAracAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSistemi.AracService.InsertAracResponse> InsertAracAsync(AracKiralamaSistemi.AracService.Arac entity) {
            AracKiralamaSistemi.AracService.InsertAracRequest inValue = new AracKiralamaSistemi.AracService.InsertAracRequest();
            inValue.Body = new AracKiralamaSistemi.AracService.InsertAracRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralamaSistemi.AracService.AracWebServiceSoap)(this)).InsertAracAsync(inValue);
        }
        
        public bool DeleteArac(int aracId) {
            return base.Channel.DeleteArac(aracId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAracAsync(int aracId) {
            return base.Channel.DeleteAracAsync(aracId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSistemi.AracService.SelectAllAracsResponse AracKiralamaSistemi.AracService.AracWebServiceSoap.SelectAllAracs(AracKiralamaSistemi.AracService.SelectAllAracsRequest request) {
            return base.Channel.SelectAllAracs(request);
        }
        
        public AracKiralamaSistemi.AracService.Arac[] SelectAllAracs() {
            AracKiralamaSistemi.AracService.SelectAllAracsRequest inValue = new AracKiralamaSistemi.AracService.SelectAllAracsRequest();
            inValue.Body = new AracKiralamaSistemi.AracService.SelectAllAracsRequestBody();
            AracKiralamaSistemi.AracService.SelectAllAracsResponse retVal = ((AracKiralamaSistemi.AracService.AracWebServiceSoap)(this)).SelectAllAracs(inValue);
            return retVal.Body.SelectAllAracsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSistemi.AracService.SelectAllAracsResponse> AracKiralamaSistemi.AracService.AracWebServiceSoap.SelectAllAracsAsync(AracKiralamaSistemi.AracService.SelectAllAracsRequest request) {
            return base.Channel.SelectAllAracsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSistemi.AracService.SelectAllAracsResponse> SelectAllAracsAsync() {
            AracKiralamaSistemi.AracService.SelectAllAracsRequest inValue = new AracKiralamaSistemi.AracService.SelectAllAracsRequest();
            inValue.Body = new AracKiralamaSistemi.AracService.SelectAllAracsRequestBody();
            return ((AracKiralamaSistemi.AracService.AracWebServiceSoap)(this)).SelectAllAracsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSistemi.AracService.SelectAracByIdResponse AracKiralamaSistemi.AracService.AracWebServiceSoap.SelectAracById(AracKiralamaSistemi.AracService.SelectAracByIdRequest request) {
            return base.Channel.SelectAracById(request);
        }
        
        public AracKiralamaSistemi.AracService.Arac SelectAracById(int aracId) {
            AracKiralamaSistemi.AracService.SelectAracByIdRequest inValue = new AracKiralamaSistemi.AracService.SelectAracByIdRequest();
            inValue.Body = new AracKiralamaSistemi.AracService.SelectAracByIdRequestBody();
            inValue.Body.aracId = aracId;
            AracKiralamaSistemi.AracService.SelectAracByIdResponse retVal = ((AracKiralamaSistemi.AracService.AracWebServiceSoap)(this)).SelectAracById(inValue);
            return retVal.Body.SelectAracByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSistemi.AracService.SelectAracByIdResponse> AracKiralamaSistemi.AracService.AracWebServiceSoap.SelectAracByIdAsync(AracKiralamaSistemi.AracService.SelectAracByIdRequest request) {
            return base.Channel.SelectAracByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSistemi.AracService.SelectAracByIdResponse> SelectAracByIdAsync(int aracId) {
            AracKiralamaSistemi.AracService.SelectAracByIdRequest inValue = new AracKiralamaSistemi.AracService.SelectAracByIdRequest();
            inValue.Body = new AracKiralamaSistemi.AracService.SelectAracByIdRequestBody();
            inValue.Body.aracId = aracId;
            return ((AracKiralamaSistemi.AracService.AracWebServiceSoap)(this)).SelectAracByIdAsync(inValue);
        }
    }
}
