//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaSistemi.CalisanService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calisan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Calisan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int calisanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soyadField;
        
        private int sirketIdField;
        
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AracKiralamaSistemi.CalisanService.Sirket sirketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AracKiralamaSistemi.CalisanService.Kullanici kullaniciField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int calisanId {
            get {
                return this.calisanIdField;
            }
            set {
                if ((this.calisanIdField.Equals(value) != true)) {
                    this.calisanIdField = value;
                    this.RaisePropertyChanged("calisanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ad {
            get {
                return this.adField;
            }
            set {
                if ((object.ReferenceEquals(this.adField, value) != true)) {
                    this.adField = value;
                    this.RaisePropertyChanged("ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string soyad {
            get {
                return this.soyadField;
            }
            set {
                if ((object.ReferenceEquals(this.soyadField, value) != true)) {
                    this.soyadField = value;
                    this.RaisePropertyChanged("soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int sirketId {
            get {
                return this.sirketIdField;
            }
            set {
                if ((this.sirketIdField.Equals(value) != true)) {
                    this.sirketIdField = value;
                    this.RaisePropertyChanged("sirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public AracKiralamaSistemi.CalisanService.Sirket sirket {
            get {
                return this.sirketField;
            }
            set {
                if ((object.ReferenceEquals(this.sirketField, value) != true)) {
                    this.sirketField = value;
                    this.RaisePropertyChanged("sirket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AracKiralamaSistemi.CalisanService.Kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sirket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sirket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int sirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sirketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresField;
        
        private ushort aracSayisiField;
        
        private System.Nullable<int> sirketPuaniField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sirketId {
            get {
                return this.sirketIdField;
            }
            set {
                if ((this.sirketIdField.Equals(value) != true)) {
                    this.sirketIdField = value;
                    this.RaisePropertyChanged("sirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sirketAdi {
            get {
                return this.sirketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.sirketAdiField, value) != true)) {
                    this.sirketAdiField = value;
                    this.RaisePropertyChanged("sirketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sehir {
            get {
                return this.sehirField;
            }
            set {
                if ((object.ReferenceEquals(this.sehirField, value) != true)) {
                    this.sehirField = value;
                    this.RaisePropertyChanged("sehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adres {
            get {
                return this.adresField;
            }
            set {
                if ((object.ReferenceEquals(this.adresField, value) != true)) {
                    this.adresField = value;
                    this.RaisePropertyChanged("adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public ushort aracSayisi {
            get {
                return this.aracSayisiField;
            }
            set {
                if ((this.aracSayisiField.Equals(value) != true)) {
                    this.aracSayisiField = value;
                    this.RaisePropertyChanged("aracSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> sirketPuani {
            get {
                return this.sirketPuaniField;
            }
            set {
                if ((this.sirketPuaniField.Equals(value) != true)) {
                    this.sirketPuaniField = value;
                    this.RaisePropertyChanged("sirketPuani");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanici", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Kullanici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullaniciAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parolaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullaniciTuruField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string kullaniciAd {
            get {
                return this.kullaniciAdField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciAdField, value) != true)) {
                    this.kullaniciAdField = value;
                    this.RaisePropertyChanged("kullaniciAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string parola {
            get {
                return this.parolaField;
            }
            set {
                if ((object.ReferenceEquals(this.parolaField, value) != true)) {
                    this.parolaField = value;
                    this.RaisePropertyChanged("parola");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string kullaniciTuru {
            get {
                return this.kullaniciTuruField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciTuruField, value) != true)) {
                    this.kullaniciTuruField = value;
                    this.RaisePropertyChanged("kullaniciTuru");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalisanService.CalisanWebServiceSoap")]
    public interface CalisanWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCalisan", ReplyAction="*")]
        AracKiralamaSistemi.CalisanService.InsertCalisanResponse InsertCalisan(AracKiralamaSistemi.CalisanService.InsertCalisanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCalisan", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSistemi.CalisanService.InsertCalisanResponse> InsertCalisanAsync(AracKiralamaSistemi.CalisanService.InsertCalisanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCalisan", ReplyAction="*")]
        bool DeleteCalisan(int calisanId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCalisan", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCalisanAsync(int calisanId);
        
        // CODEGEN: Generating message contract since element name SelectAllCalisansResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllCalisans", ReplyAction="*")]
        AracKiralamaSistemi.CalisanService.SelectAllCalisansResponse SelectAllCalisans(AracKiralamaSistemi.CalisanService.SelectAllCalisansRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllCalisans", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSistemi.CalisanService.SelectAllCalisansResponse> SelectAllCalisansAsync(AracKiralamaSistemi.CalisanService.SelectAllCalisansRequest request);
        
        // CODEGEN: Generating message contract since element name SelectCalisanByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCalisanById", ReplyAction="*")]
        AracKiralamaSistemi.CalisanService.SelectCalisanByIdResponse SelectCalisanById(AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCalisanById", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralamaSistemi.CalisanService.SelectCalisanByIdResponse> SelectCalisanByIdAsync(AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCalisanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCalisan", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.CalisanService.InsertCalisanRequestBody Body;
        
        public InsertCalisanRequest() {
        }
        
        public InsertCalisanRequest(AracKiralamaSistemi.CalisanService.InsertCalisanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCalisanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSistemi.CalisanService.Calisan entity;
        
        public InsertCalisanRequestBody() {
        }
        
        public InsertCalisanRequestBody(AracKiralamaSistemi.CalisanService.Calisan entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCalisanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCalisanResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.CalisanService.InsertCalisanResponseBody Body;
        
        public InsertCalisanResponse() {
        }
        
        public InsertCalisanResponse(AracKiralamaSistemi.CalisanService.InsertCalisanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCalisanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertCalisanResult;
        
        public InsertCalisanResponseBody() {
        }
        
        public InsertCalisanResponseBody(bool InsertCalisanResult) {
            this.InsertCalisanResult = InsertCalisanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllCalisansRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllCalisans", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.CalisanService.SelectAllCalisansRequestBody Body;
        
        public SelectAllCalisansRequest() {
        }
        
        public SelectAllCalisansRequest(AracKiralamaSistemi.CalisanService.SelectAllCalisansRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllCalisansRequestBody {
        
        public SelectAllCalisansRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllCalisansResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllCalisansResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.CalisanService.SelectAllCalisansResponseBody Body;
        
        public SelectAllCalisansResponse() {
        }
        
        public SelectAllCalisansResponse(AracKiralamaSistemi.CalisanService.SelectAllCalisansResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllCalisansResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSistemi.CalisanService.Calisan[] SelectAllCalisansResult;
        
        public SelectAllCalisansResponseBody() {
        }
        
        public SelectAllCalisansResponseBody(AracKiralamaSistemi.CalisanService.Calisan[] SelectAllCalisansResult) {
            this.SelectAllCalisansResult = SelectAllCalisansResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCalisanByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCalisanById", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequestBody Body;
        
        public SelectCalisanByIdRequest() {
        }
        
        public SelectCalisanByIdRequest(AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCalisanByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int calisanId;
        
        public SelectCalisanByIdRequestBody() {
        }
        
        public SelectCalisanByIdRequestBody(int calisanId) {
            this.calisanId = calisanId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCalisanByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCalisanByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralamaSistemi.CalisanService.SelectCalisanByIdResponseBody Body;
        
        public SelectCalisanByIdResponse() {
        }
        
        public SelectCalisanByIdResponse(AracKiralamaSistemi.CalisanService.SelectCalisanByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCalisanByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralamaSistemi.CalisanService.Calisan SelectCalisanByIdResult;
        
        public SelectCalisanByIdResponseBody() {
        }
        
        public SelectCalisanByIdResponseBody(AracKiralamaSistemi.CalisanService.Calisan SelectCalisanByIdResult) {
            this.SelectCalisanByIdResult = SelectCalisanByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalisanWebServiceSoapChannel : AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalisanWebServiceSoapClient : System.ServiceModel.ClientBase<AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap>, AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap {
        
        public CalisanWebServiceSoapClient() {
        }
        
        public CalisanWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalisanWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalisanWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalisanWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSistemi.CalisanService.InsertCalisanResponse AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap.InsertCalisan(AracKiralamaSistemi.CalisanService.InsertCalisanRequest request) {
            return base.Channel.InsertCalisan(request);
        }
        
        public bool InsertCalisan(AracKiralamaSistemi.CalisanService.Calisan entity) {
            AracKiralamaSistemi.CalisanService.InsertCalisanRequest inValue = new AracKiralamaSistemi.CalisanService.InsertCalisanRequest();
            inValue.Body = new AracKiralamaSistemi.CalisanService.InsertCalisanRequestBody();
            inValue.Body.entity = entity;
            AracKiralamaSistemi.CalisanService.InsertCalisanResponse retVal = ((AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap)(this)).InsertCalisan(inValue);
            return retVal.Body.InsertCalisanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSistemi.CalisanService.InsertCalisanResponse> AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap.InsertCalisanAsync(AracKiralamaSistemi.CalisanService.InsertCalisanRequest request) {
            return base.Channel.InsertCalisanAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSistemi.CalisanService.InsertCalisanResponse> InsertCalisanAsync(AracKiralamaSistemi.CalisanService.Calisan entity) {
            AracKiralamaSistemi.CalisanService.InsertCalisanRequest inValue = new AracKiralamaSistemi.CalisanService.InsertCalisanRequest();
            inValue.Body = new AracKiralamaSistemi.CalisanService.InsertCalisanRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap)(this)).InsertCalisanAsync(inValue);
        }
        
        public bool DeleteCalisan(int calisanId) {
            return base.Channel.DeleteCalisan(calisanId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCalisanAsync(int calisanId) {
            return base.Channel.DeleteCalisanAsync(calisanId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSistemi.CalisanService.SelectAllCalisansResponse AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap.SelectAllCalisans(AracKiralamaSistemi.CalisanService.SelectAllCalisansRequest request) {
            return base.Channel.SelectAllCalisans(request);
        }
        
        public AracKiralamaSistemi.CalisanService.Calisan[] SelectAllCalisans() {
            AracKiralamaSistemi.CalisanService.SelectAllCalisansRequest inValue = new AracKiralamaSistemi.CalisanService.SelectAllCalisansRequest();
            inValue.Body = new AracKiralamaSistemi.CalisanService.SelectAllCalisansRequestBody();
            AracKiralamaSistemi.CalisanService.SelectAllCalisansResponse retVal = ((AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap)(this)).SelectAllCalisans(inValue);
            return retVal.Body.SelectAllCalisansResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSistemi.CalisanService.SelectAllCalisansResponse> AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap.SelectAllCalisansAsync(AracKiralamaSistemi.CalisanService.SelectAllCalisansRequest request) {
            return base.Channel.SelectAllCalisansAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSistemi.CalisanService.SelectAllCalisansResponse> SelectAllCalisansAsync() {
            AracKiralamaSistemi.CalisanService.SelectAllCalisansRequest inValue = new AracKiralamaSistemi.CalisanService.SelectAllCalisansRequest();
            inValue.Body = new AracKiralamaSistemi.CalisanService.SelectAllCalisansRequestBody();
            return ((AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap)(this)).SelectAllCalisansAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralamaSistemi.CalisanService.SelectCalisanByIdResponse AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap.SelectCalisanById(AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequest request) {
            return base.Channel.SelectCalisanById(request);
        }
        
        public AracKiralamaSistemi.CalisanService.Calisan SelectCalisanById(int calisanId) {
            AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequest inValue = new AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequest();
            inValue.Body = new AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequestBody();
            inValue.Body.calisanId = calisanId;
            AracKiralamaSistemi.CalisanService.SelectCalisanByIdResponse retVal = ((AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap)(this)).SelectCalisanById(inValue);
            return retVal.Body.SelectCalisanByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralamaSistemi.CalisanService.SelectCalisanByIdResponse> AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap.SelectCalisanByIdAsync(AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequest request) {
            return base.Channel.SelectCalisanByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralamaSistemi.CalisanService.SelectCalisanByIdResponse> SelectCalisanByIdAsync(int calisanId) {
            AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequest inValue = new AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequest();
            inValue.Body = new AracKiralamaSistemi.CalisanService.SelectCalisanByIdRequestBody();
            inValue.Body.calisanId = calisanId;
            return ((AracKiralamaSistemi.CalisanService.CalisanWebServiceSoap)(this)).SelectCalisanByIdAsync(inValue);
        }
    }
}
